apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVTFhvNWpvN3I5OUpuUnMybFQ5SythMGVHT0Rnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSTBNVEV3TWpJd05UQXhPRm9YRFRJME1USXdNakl3TlRBeE9Gb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXRkS2I4Vm5Mdjg2Wi9CN0VSeWtHUnlWTEhpWHBnK2wxUEVrYgpHb2UrNXlEUFFDWkNqNFVUMXJ4U1VISFlmY1hXSVZsUGpOcGIzUDArR1ZyWjdBSDJOUVZIYlRKTlRuSzB2Ti9nCm9Ea3d0SDFkbjFDaGdwZUh2aFBsZ3dWTlRMaWg0SDN2UzZZNUY3NFlyM0VIa0Q0QTA5NittSGpoa2prWXQ2WXoKbi92a0w3aGxBQlhkc0EzcXRCODRMRk51Yk1hRi9JLzYxQjIvMVA2dnNHTGlGVy9uRTFUQm9sblJpam91Ri92aQpBZThZSllaWFlnZmlBejdhVG9maG1DZjJqRGVLVUNiVzRzblpLYXZTd0NRV1hrL2hORE9Sb2xrYXpUSmlKQUloCmpCbm9IaFZDb2I3Wi9JUElXTVRMYlpDSkdBbS93bFVJaHErSzZCZXN6TFpGK1ZvRDlRSURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVQWtjSGxpSXovdVIwSDJRNzd3VTcwbWY3N3NZd0h3WURWUjBqQkJnd0ZvQVVBa2NIbGlJegovdVIwSDJRNzd3VTcwbWY3N3NZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFPZVBwRHA1dXRZdERZVkZLMWNreDdmN2YrTlVSd2RGQjRvdVR4L0VBaXpzcG5uVEYyVHRON1QyU3dkakIKaDluNWlmMCszSmVFZHBiK1NvK3dqTVBsd2NUejNNWmNVYXZpVW1iaTNNMXA1bGliak9sU1QvaXJoSGZRQUNVSgp6YzFSeTZ1Z3JZMVNMSVhPOUpra2Q5bGdTOG9EQmF2K21LY0tNNlRzRHB3dk11VWwzM25KU2RRUlVVSDJSZmRvCkxHYldkM3hsdlJKd0lzdjZrUk8yT2Q0dWZzczdoWFEyK016N29wUGVza0RkZS9nUVFpT3ZsRWZTMU1nSmRQdG4KVVFIWHdhQ2N0SE9FeDJac2I1Y0pSZWJMR0dCUjdEcHlYdTd4TXAwQ0NUV3NGTU96OU5XUGpnRjUxUnlIaCtudwpwcG1ZcVVCSHhzMzJWNkpzOVF1dCtXd1RFQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None