apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2024-11-03T23:06:35Z"
  generation: 1
  name: collectors.monitoring.controller
  resourceVersion: "1222"
  uid: c9c160c3-4abb-49cd-bb45-c14a8cc8b670
spec:
  conversion:
    strategy: None
  group: monitoring.controller
  names:
    kind: Collector
    listKind: CollectorList
    plural: collectors
    shortNames:
      - collect
    singular: collector
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                image:
                  type: string
                name:
                  type: string
                replicas:
                  type: integer
              type: object
          type: object
      served: true
      storage: true
status:
  acceptedNames:
    kind: Collector
    listKind: CollectorList
    plural: collectors
    shortNames:
      - collect
    singular: collector
  conditions:
    - lastTransitionTime: "2024-11-03T23:06:35Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2024-11-03T23:06:35Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1