{{- if .Values.springApp.secrets }}
  {{- range .Values.springApp.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "spring-app.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ .secretKey }}: {{ .secretValue | b64enc | quote }}
  {{- end }}
{{- end }}