{{- if .Values.springApp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spring-app.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
{{- end -}}