apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2024-11-02T08:59:03Z"
  name: michelle-storage-admin
  resourceVersion: "1257"
  uid: d8d092e0-71c7-4bc4-8bbb-c15e17184bad
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storage-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: michelle