apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2024-11-02T08:57:22Z"
  name: storage-admin
  resourceVersion: "1225"
  uid: 3b1104cb-1639-4f57-987b-88108fa33fea
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - '*'
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - '*'