#------------------------
# NOT DEPLOYED
#------------------------
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store-1
  namespace: dev-ns
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: spring-app-sa

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets-1
  namespace: dev-ns
spec:
  refreshInterval: 1m  # How often to sync secrets
  secretStoreRef:
    name: aws-secret-store-1  # References the ext SecretStore we created above
    kind: SecretStore       # Could be ClusterSecretStore if using that instead
  target:
    name: k8s-secret-1  # Name of the K8s Secret to create
    creationPolicy: Owner
  data:
    - secretKey: tls.crt  # Key in K8s Secret
      remoteRef:
        key: automation/AAMMDB7723/viewfile/crfbackend-deo3  # AWS Secret name
        property: certificate  # Key in AWS Secret
    - secretKey: tls.key
      remoteRef:
        key: automation/AAMMDB7723/viewfile/crfbackend-deo3
        property: private_key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets-2
  namespace: dev-ns
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secret-store-1
    kind: SecretStore
  target:
    name: k8s-secret-2 # Name of the K8s Secret to create
    creationPolicy: Owner
  data:
    - secretKey: key-1 # Key in K8s Secret
      remoteRef:
        key: aws-secret-mananger-1  # AWS Secret name
        property: value-1 # Key in AWS Secret
    - secretKey: key-2
      remoteRef:
        key: aws-secret-mananger-1
        property: value-2