apiVersion: v1
kind: Pod
metadata:
  name: postgres-14
  namespace: dev1-manifest
  labels:
    app: postgres
    version: "14"
spec:
  containers:
    - name: postgres
      image: postgres:14
      env:
        - name: POSTGRES_PASSWORD
          value: "primary_pass"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
      ports:
        - containerPort: 5432
          name: postgres-port
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
  volumes:
    - name: postgres-data
      emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  namespace: dev1-manifest
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432